//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonobo.Irc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bonobo.Irc.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPAddress or port are not valid..
        /// </summary>
        internal static string AddressAndPortException {
            get {
                return ResourceManager.GetString("AddressAndPortException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Registred Error - {0}.
        /// </summary>
        internal static string AlreadyRegistred {
            get {
                return ResourceManager.GetString("AlreadyRegistred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection wasn&apos;t established with target server.
        /// </summary>
        internal static string ConnectionNotEstablished {
            get {
                return ResourceManager.GetString("ConnectionNotEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errorneus Nickname Error - {0} {1}.
        /// </summary>
        internal static string ErrorneusNickname {
            get {
                return ResourceManager.GetString("ErrorneusNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need More Params Error - {0} has invalid arguments..
        /// </summary>
        internal static string NeedMoreParams {
            get {
                return ResourceManager.GetString("NeedMoreParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick Collision Error - {0} {1}.
        /// </summary>
        internal static string NicknameCollision {
            get {
                return ResourceManager.GetString("NicknameCollision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname in Use Error - {0} {1}.
        /// </summary>
        internal static string NicknameInUse {
            get {
                return ResourceManager.GetString("NicknameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Nickname Error - {0}.
        /// </summary>
        internal static string NoNickname {
            get {
                return ResourceManager.GetString("NoNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Registred Error - {0}.
        /// </summary>
        internal static string NotRegistred {
            get {
                return ResourceManager.GetString("NotRegistred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Server Info.
        /// </summary>
        internal static string ServerHeader {
            get {
                return ResourceManager.GetString("ServerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown server response: {0}.
        /// </summary>
        internal static string UnknownServerResponse {
            get {
                return ResourceManager.GetString("UnknownServerResponse", resourceCulture);
            }
        }
    }
}
